name: Docker Image CI
env:
  uuid: uuidgen
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  job0-install:
    runs-on: self-hosted
    steps:
    - run: echo "UUID sample is $uuid"
    - uses: actions/checkout@v1
    - name: Install Docker
      run: sudo chmod +777 code/* && sudo ./code/install_docker.sh
  job1-build:
    runs-on: self-hosted
    needs: job0-install
    steps:   
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: sudo docker build -t ml-repo:$GITHUB_RUN_ID .
  job2-run:
    needs: [job0-install, job1-build]
    runs-on: self-hosted
    timeout-minutes: 1
    steps:
    - uses: actions/checkout@v2
    - name: Run a container
      run: sudo docker run --name mlcont -p 6666:6666 ml-repo:$GITHUB_RUN_ID
  job3-test:
    if: ${{ always() }}
    needs: [job0-install, job1-build, job2-run]
    runs-on: self-hosted
    timeout-minutes: 6
    steps:
    - uses: actions/checkout@v3
    - name: test the inference end point
      run: sudo docker exec mlcont sh && ./code/test.sh 
  job4-exit:
    needs: [job0-install, job1-build, job2-run, job3-test]
    runs-on: self-hosted
    timeout-minutes: 6
    steps:
    - uses: actions/checkout@v3
    - name: exit from container
      run: sudo docker stop mlcont && sudo docker rm mlcont 
      
    
