name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  job1-build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: sudo docker build -t ml-repo -f Dockerfile
  job2-run:
    needs: job1-build
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run a container
      run: sudo docker run --name mlcont -p 6666:6666 ml-repo
  job3-test:
    needs: [job1-build, job2-run]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: test the inference end point
      run: sudo docker exec mlcont sh && python code/test.py "http://localhost:6666"
      
    
