name: Docker Image CI
env:
  ip: ${{vars.SERVER_IP}}
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  job0-install:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Install Docker
      run: sudo chmod +777 code/* && sudo ./code/install_docker.sh
  job1-build:
    runs-on: self-hosted
    needs: job0-install
    steps:   
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: sudo docker build -t ml-repo:$GITHUB_RUN_ID .
  job2-run:
    needs: [job0-install, job1-build]
    runs-on: self-hosted
    steps:
    - run: |
        echo "{cont}={$GITHUB_RUN_ID}" >> "$GITHUB_ENV"
    - uses: actions/checkout@v2
    - id: job2
    - name: RunContainer
      continue-on-error: true
      run: timeout 1 sudo docker run -p 6666:6666 ml-repo:$GITHUB_RUN_ID
    - uses: actions/checkout@v2
    - name: success
    - id: setSuccess
      if: steps.job2.outcome == 'cancelled'
      run: exit 0
      
  job3-test:
    if: ${{ always() }}
    needs: [job0-install, job1-build, job2-run]
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
    - uses: actions/checkout@v3
    - name: test the inference end point
      run:  sudo chmod +777 test/* && sudo pip install -r test/req_test.txt && ./test/test.sh $ip
      
    
